### ISSUE TITLE
Current state of this project and one fix

### ISSUE THREAD

**Issue by Meister1593** [SMemsky/Stranded2pp#1]
I was checking my really old files and i noticed Stranded 2 in them, i thought it was cool to try out
I'm on linux currently and thought what if there an active development of such project, so i googled and found out this.

Immediately compiled, fixed in [this](https://github.com/dexter3k/Stranded2pp/blob/master/source/graphics/BmpFont.cpp) file error, that caused by updated gcc (just add `#include <stdexcept>` at top of this file to fix issue) and got mods folder from original game.

It ran, but it seems nothing is implemented yet? like, every button just shows unreal logo and drops back to menu.

**Comment by dexter3k** [comment]
Hi, its great to see that after so many years people still play this game :D

I worked on this project many years ago, but ended up abandoning it due to lack of time and motivation. It is in very early stages of development right now and I don't believe that's going to ever change. Recently I started working on a [new implementation](https://github.com/dexter3k/stranded2_web) of Stranded 2 in JavaScript and WebGL, but while I've had more success with it, its still not playable. Maybe now I'll consider spending more time on it :)

Also if you're interested in running original Stranded 2 on Linux then I'll recommend to just use Wine and a [patched exe](https://github.com/aroidzap/Stranded-2-Boost/releases/tag/1.0a) by [aroidzap](https://github.com/aroidzap).

If you think Stranded 2 is a great game which derserves to live forever then feel free to drop [me a message on Telegram](https://t.me/dexter3k).
